import 'core-js/features/array/find'
import 'core-js/features/array/find-index'
import 'core-js/features/array/from'
import 'core-js/features/array/includes'
import 'core-js/features/object/assign'
import 'core-js/features/string/includes'
import 'core-js/features/set'
import 'core-js/features/map'
